export default {
    IGNORE_EMPTY: "ignoreEmpty",
    VOICE: "voice",
    LANGUAGE: "language",
    LANGUAGE_CODE: "languageCode",
    DEFAULT_ENTER_ALERT: "enterAlert",
    DEFAULT_EXIT_ALERT: "exitAlert",
    VERSION: "version",
    USER_VOICES: "userVoices",
    USER_ALERTS: "userAlerts",
    ANNOUNCEMENT_CHANNEL_ID: "announcementChannelId",
    ENABLED: "enabled",
    USER_SNEAK: "userSneak",
    SNEAKING_ALLOWED: "sneakingAllowed",
}